TASK_NAME: 'image_style_transform'

MODEL:
  NAME: 'conditional_gan'
  DEVICE: 'cuda'
  DEVICE_IDS: [0]
  SEED: 1
  PRETRAINED: False
  PRETRAIN_PATH: ''
  DROPOUT: 0.5
  NORM: 'batch'
  INIT: 'normal'
  INIT_GAIN: 0.02
  CONSIST: 
    G: 'unet_256'
    D: 3

LOSS:
  NAME: ['gan_loss', 'L1Loss']
  LAMBDA_A: 10
  LAMBDA_B: 10
  LAMBDA_IDENTITY: 0.5
  LAMBDA_L1: 100.0

INPUT:
  TYPE: 'image'
  CHANNEL: 3
  SIZE: [286, 286]
  GRAY_MEAN: [0.5]
  GRAY_STD: [0.5]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  MODALITY: 'RGB'
  DIRECTION: True
  POOL_SIZE: 50

PROCESS:
  RESIZE: True
  CROP: True
  CROP_SIZE: [256, 256]
  FLIP: False
  FLIP_P: 0.5
  TOTENSOR: True
  NORM: True

OUTPUT:
  TYPE: 'image'
  CHANNEL: 3
  SIZE: [224, 224]

DATASET:
  NAME: 'facades'
  TYPE: 'aligned'
  ROOT_DIR: '/mnt/disk3/quyi/data/facades'
  MAX_SIZE: 'inf'
  
DATALOADER:
  SHUFFLE: True
  NUM_WORKERS: 4
  BATCH_SIZE: 1

SOLVER:
  OPTIM_NAME: "Adam"
  OPTIM_BETA: 0.5
  LR_SCHEDULER: 'linear'
  BASE_LR: 0.0002
  # lr_init_epoch + lr_decay_epoch = max_epoch
  LR_DECAY_EPOCH: 100
  LR_INIT_EPOCH: 100
  LR_DECAY_ITERS:  50

TRAIN:
  START_EPOCH: 0
  MAX_EPOCH: 200
  ADD_EPOCH: 0
  IS_TRAIN: True

METRIC:
  NAME: []

TEST:
  BATCH_SIZE: 1
  WEIGHT: ""

CHECKPOINT:
  RESUME: 'none'
  CHECKNAME: ''