MODEL:
  NAME: 'cycle_gan'
  DEVICE: 'cuda'
  DEVICE_IDS: [0]
  SEED: 1
  PRETRAINED: False
  PRETRAIN_PATH: ''
  DROPOUT: 0.5
  
LOSS:
  NAME: 'cycle_gan_loss'
  LAMBDA_A: 10
  LAMBDA_B: 10
  LAMBDA_IDENTITY: 0.5

INPUT:
  TYPE: 'image'
  CHANNEL: 3
  SIZE: [224, 224]
  GRAY_MEAN: [0.5]
  GRAY_STD: [0.5]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  MODALITY: 'RGB'
  DIRECTION: True

PROCESS:
  RESIZE: True
  CROP: True
  CROP_SIZE: [256, 256]
  FLIP: False
  FLIP_P: 0.5
  TOTENSOR: True

OUTPUT:
  TYPE: 'image'
  CHANNEL: 3
  SIZE: [224, 224]

DATASET:
  NAME: 'horse2zebra'
  TYPE: 'unaligned'
  ROOT_DIR: '/mnt/disk3/quyi/horse2zebra'
  MAX_SIZE: 'inf'
  
DATALOADER:
  NUM_WORKERS: 8
  BATCH_SIZE: 128

SOLVER:
  OPTIMIZER_NAME: "Adam"
  LR_SCHEDULER: 'linear'

TRAIN:
  IS_TRAIN: True

TEST:
  BATCH_SIZE: 128
  WEIGHT: ""

CHECKPOINT:
  RESUME: 'none'
  CHECKNAME: ''