MODEL:
  NAME: 'cycle_gan'
  DEVICE: 'cuda'
  DEVICE_IDS: [0]
  SEED: 1
  PRETRAINED: False
  PRETRAIN_PATH: ''
  LOSS: 'cycle_gan_loss'
  DROPOUT: 0.5

INPUT:
  SIZE: [224, 224]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  MODALITY: 'RGB'

DATASET:
  NAME: 'horse2zebra'
  TYPE: 'unaligned'
  ROOT_DIR: '/mnt/disk3/quyi/horse2zebra'
  
DATALOADER:
  NUM_WORKERS: 8
  BATCH_SIZE: 128

SOLVER:
  OPTIMIZER_NAME: "Adam"
  LR_SCHEDULER: 'linear'

TEST:
  BATCH_SIZE: 128
  WEIGHT: ""

CHECKPOINT:
  RESUME: 'none'
  CHECKNAME: ''